// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cart.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addToCart = `-- name: AddToCart :one
INSERT INTO cart_items (user_id, product_id, quantity)
VALUES (?, ?, ?)
ON CONFLICT(user_id, product_id) DO UPDATE SET quantity = cart_items.quantity + excluded.quantity
RETURNING id, user_id, product_id, quantity, created_at
`

type AddToCartParams struct {
	UserID    int64 `json:"user_id"`
	ProductID int64 `json:"product_id"`
	Quantity  int64 `json:"quantity"`
}

func (q *Queries) AddToCart(ctx context.Context, arg AddToCartParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, addToCart, arg.UserID, arg.ProductID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items WHERE user_id = ?
`

func (q *Queries) ClearCart(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, clearCart, userID)
	return err
}

const getCartItem = `-- name: GetCartItem :one
SELECT id, user_id, product_id, quantity, created_at FROM cart_items WHERE user_id = ? AND product_id = ? LIMIT 1
`

type GetCartItemParams struct {
	UserID    int64 `json:"user_id"`
	ProductID int64 `json:"product_id"`
}

func (q *Queries) GetCartItem(ctx context.Context, arg GetCartItemParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, getCartItem, arg.UserID, arg.ProductID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const getCartItemCount = `-- name: GetCartItemCount :one
SELECT COALESCE(SUM(quantity), 0) as count FROM cart_items WHERE user_id = ?
`

func (q *Queries) GetCartItemCount(ctx context.Context, userID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getCartItemCount, userID)
	var count interface{}
	err := row.Scan(&count)
	return count, err
}

const getCartItems = `-- name: GetCartItems :many
SELECT ci.id, ci.user_id, ci.product_id, ci.quantity, ci.created_at, p.name as product_name, p.price as product_price, p.image_url as product_image
FROM cart_items ci
JOIN products p ON ci.product_id = p.id
WHERE ci.user_id = ?
`

type GetCartItemsRow struct {
	ID           int64          `json:"id"`
	UserID       int64          `json:"user_id"`
	ProductID    int64          `json:"product_id"`
	Quantity     int64          `json:"quantity"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	ProductName  string         `json:"product_name"`
	ProductPrice int64          `json:"product_price"`
	ProductImage sql.NullString `json:"product_image"`
}

func (q *Queries) GetCartItems(ctx context.Context, userID int64) ([]GetCartItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCartItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCartItemsRow{}
	for rows.Next() {
		var i GetCartItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.Quantity,
			&i.CreatedAt,
			&i.ProductName,
			&i.ProductPrice,
			&i.ProductImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCartTotal = `-- name: GetCartTotal :one
SELECT COALESCE(SUM(ci.quantity * p.price), 0) as total
FROM cart_items ci
JOIN products p ON ci.product_id = p.id
WHERE ci.user_id = ?
`

func (q *Queries) GetCartTotal(ctx context.Context, userID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getCartTotal, userID)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const removeFromCart = `-- name: RemoveFromCart :exec
DELETE FROM cart_items WHERE user_id = ? AND product_id = ?
`

type RemoveFromCartParams struct {
	UserID    int64 `json:"user_id"`
	ProductID int64 `json:"product_id"`
}

func (q *Queries) RemoveFromCart(ctx context.Context, arg RemoveFromCartParams) error {
	_, err := q.db.ExecContext(ctx, removeFromCart, arg.UserID, arg.ProductID)
	return err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :exec
UPDATE cart_items SET quantity = ? WHERE user_id = ? AND product_id = ?
`

type UpdateCartItemQuantityParams struct {
	Quantity  int64 `json:"quantity"`
	UserID    int64 `json:"user_id"`
	ProductID int64 `json:"product_id"`
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) error {
	_, err := q.db.ExecContext(ctx, updateCartItemQuantity, arg.Quantity, arg.UserID, arg.ProductID)
	return err
}
