// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type CartItem struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	ProductID int64        `json:"product_id"`
	Quantity  int64        `json:"quantity"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Order struct {
	ID                    int64          `json:"id"`
	UserID                int64          `json:"user_id"`
	StripePaymentIntentID sql.NullString `json:"stripe_payment_intent_id"`
	Status                sql.NullString `json:"status"`
	Total                 int64          `json:"total"`
	ShippingAddress       sql.NullString `json:"shipping_address"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	UpdatedAt             sql.NullTime   `json:"updated_at"`
}

type OrderItem struct {
	ID        int64 `json:"id"`
	OrderID   int64 `json:"order_id"`
	ProductID int64 `json:"product_id"`
	Quantity  int64 `json:"quantity"`
	Price     int64 `json:"price"`
}

type Product struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	Price       int64          `json:"price"`
	Category    string         `json:"category"`
	Collection  sql.NullString `json:"collection"`
	ImageUrl    sql.NullString `json:"image_url"`
	Featured    sql.NullInt64  `json:"featured"`
	InStock     sql.NullInt64  `json:"in_stock"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID        int64          `json:"id"`
	ClerkID   string         `json:"clerk_id"`
	Email     string         `json:"email"`
	FirstName sql.NullString `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}
