// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, stripe_payment_intent_id, status, total, shipping_address)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, stripe_payment_intent_id, status, total, shipping_address, created_at, updated_at
`

type CreateOrderParams struct {
	UserID                int64          `json:"user_id"`
	StripePaymentIntentID sql.NullString `json:"stripe_payment_intent_id"`
	Status                sql.NullString `json:"status"`
	Total                 int64          `json:"total"`
	ShippingAddress       sql.NullString `json:"shipping_address"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.UserID,
		arg.StripePaymentIntentID,
		arg.Status,
		arg.Total,
		arg.ShippingAddress,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StripePaymentIntentID,
		&i.Status,
		&i.Total,
		&i.ShippingAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, quantity, price)
VALUES (?, ?, ?, ?)
RETURNING id, order_id, product_id, quantity, price
`

type CreateOrderItemParams struct {
	OrderID   int64 `json:"order_id"`
	ProductID int64 `json:"product_id"`
	Quantity  int64 `json:"quantity"`
	Price     int64 `json:"price"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, stripe_payment_intent_id, status, total, shipping_address, created_at, updated_at FROM orders WHERE id = ? LIMIT 1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StripePaymentIntentID,
		&i.Status,
		&i.Total,
		&i.ShippingAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByPaymentIntent = `-- name: GetOrderByPaymentIntent :one
SELECT id, user_id, stripe_payment_intent_id, status, total, shipping_address, created_at, updated_at FROM orders WHERE stripe_payment_intent_id = ? LIMIT 1
`

func (q *Queries) GetOrderByPaymentIntent(ctx context.Context, stripePaymentIntentID sql.NullString) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByPaymentIntent, stripePaymentIntentID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StripePaymentIntentID,
		&i.Status,
		&i.Total,
		&i.ShippingAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT oi.id, oi.order_id, oi.product_id, oi.quantity, oi.price, p.name as product_name, p.image_url as product_image
FROM order_items oi
JOIN products p ON oi.product_id = p.id
WHERE oi.order_id = ?
`

type GetOrderItemsRow struct {
	ID           int64          `json:"id"`
	OrderID      int64          `json:"order_id"`
	ProductID    int64          `json:"product_id"`
	Quantity     int64          `json:"quantity"`
	Price        int64          `json:"price"`
	ProductName  string         `json:"product_name"`
	ProductImage sql.NullString `json:"product_image"`
}

func (q *Queries) GetOrderItems(ctx context.Context, orderID int64) ([]GetOrderItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrderItemsRow{}
	for rows.Next() {
		var i GetOrderItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.Price,
			&i.ProductName,
			&i.ProductImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOrders = `-- name: ListUserOrders :many
SELECT id, user_id, stripe_payment_intent_id, status, total, shipping_address, created_at, updated_at FROM orders WHERE user_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListUserOrdersParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListUserOrders(ctx context.Context, arg ListUserOrdersParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listUserOrders, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StripePaymentIntentID,
			&i.Status,
			&i.Total,
			&i.ShippingAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderPaymentIntent = `-- name: UpdateOrderPaymentIntent :exec
UPDATE orders SET stripe_payment_intent_id = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateOrderPaymentIntentParams struct {
	StripePaymentIntentID sql.NullString `json:"stripe_payment_intent_id"`
	ID                    int64          `json:"id"`
}

func (q *Queries) UpdateOrderPaymentIntent(ctx context.Context, arg UpdateOrderPaymentIntentParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderPaymentIntent, arg.StripePaymentIntentID, arg.ID)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateOrderStatusParams struct {
	Status sql.NullString `json:"status"`
	ID     int64          `json:"id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatus, arg.Status, arg.ID)
	return err
}
