// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM products WHERE in_stock = 1
`

func (q *Queries) CountProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsByCategory = `-- name: CountProductsByCategory :one
SELECT COUNT(*) FROM products WHERE category = ? AND in_stock = 1
`

func (q *Queries) CountProductsByCategory(ctx context.Context, category string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProductsByCategory, category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, slug, description, price, category, collection, image_url, featured)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, slug, description, price, category, collection, image_url, featured, in_stock, created_at, updated_at
`

type CreateProductParams struct {
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	Price       int64          `json:"price"`
	Category    string         `json:"category"`
	Collection  sql.NullString `json:"collection"`
	ImageUrl    sql.NullString `json:"image_url"`
	Featured    sql.NullInt64  `json:"featured"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Price,
		arg.Category,
		arg.Collection,
		arg.ImageUrl,
		arg.Featured,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.Category,
		&i.Collection,
		&i.ImageUrl,
		&i.Featured,
		&i.InStock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = ?
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, slug, description, price, category, collection, image_url, featured, in_stock, created_at, updated_at FROM products WHERE id = ? LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.Category,
		&i.Collection,
		&i.ImageUrl,
		&i.Featured,
		&i.InStock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, name, slug, description, price, category, collection, image_url, featured, in_stock, created_at, updated_at FROM products WHERE slug = ? LIMIT 1
`

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductBySlug, slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.Category,
		&i.Collection,
		&i.ImageUrl,
		&i.Featured,
		&i.InStock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFeaturedProducts = `-- name: ListFeaturedProducts :many
SELECT id, name, slug, description, price, category, collection, image_url, featured, in_stock, created_at, updated_at FROM products WHERE featured = 1 AND in_stock = 1 ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) ListFeaturedProducts(ctx context.Context, limit int64) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listFeaturedProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.Category,
			&i.Collection,
			&i.ImageUrl,
			&i.Featured,
			&i.InStock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, slug, description, price, category, collection, image_url, featured, in_stock, created_at, updated_at FROM products WHERE in_stock = 1 ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListProductsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.Category,
			&i.Collection,
			&i.ImageUrl,
			&i.Featured,
			&i.InStock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many
SELECT id, name, slug, description, price, category, collection, image_url, featured, in_stock, created_at, updated_at FROM products WHERE category = ? AND in_stock = 1 ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListProductsByCategoryParams struct {
	Category string `json:"category"`
	Limit    int64  `json:"limit"`
	Offset   int64  `json:"offset"`
}

func (q *Queries) ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByCategory, arg.Category, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.Category,
			&i.Collection,
			&i.ImageUrl,
			&i.Featured,
			&i.InStock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCollection = `-- name: ListProductsByCollection :many
SELECT id, name, slug, description, price, category, collection, image_url, featured, in_stock, created_at, updated_at FROM products WHERE collection = ? AND in_stock = 1 ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListProductsByCollectionParams struct {
	Collection sql.NullString `json:"collection"`
	Limit      int64          `json:"limit"`
	Offset     int64          `json:"offset"`
}

func (q *Queries) ListProductsByCollection(ctx context.Context, arg ListProductsByCollectionParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByCollection, arg.Collection, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.Category,
			&i.Collection,
			&i.ImageUrl,
			&i.Featured,
			&i.InStock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT id, name, slug, description, price, category, collection, image_url, featured, in_stock, created_at, updated_at FROM products WHERE (name LIKE ? OR description LIKE ?) AND in_stock = 1 ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type SearchProductsParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Limit       int64          `json:"limit"`
	Offset      int64          `json:"offset"`
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, searchProducts,
		arg.Name,
		arg.Description,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.Category,
			&i.Collection,
			&i.ImageUrl,
			&i.Featured,
			&i.InStock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products SET name = ?, description = ?, price = ?, category = ?, collection = ?, image_url = ?, featured = ?, in_stock = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateProductParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       int64          `json:"price"`
	Category    string         `json:"category"`
	Collection  sql.NullString `json:"collection"`
	ImageUrl    sql.NullString `json:"image_url"`
	Featured    sql.NullInt64  `json:"featured"`
	InStock     sql.NullInt64  `json:"in_stock"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Category,
		arg.Collection,
		arg.ImageUrl,
		arg.Featured,
		arg.InStock,
		arg.ID,
	)
	return err
}
